service: nodeless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256

functions:
  hello:
    handler: src/handler.hello
  addUser:
    handler: src/addUser/handler.addUser