service: nodeless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256

functions:
  hello:
    handler: src/handler.hello
  addUser:
    handler: src/addUser/handler.addUser
  loginUser:
    handler: src/loginUser/handler.loginUser
  setIntroduction:
    handler: src/setIntroduction/handler.setIntroduction
  getIntroduction:
    handler: src/getIntroduction/handler.getIntroduction
  sendForm:
    handler: src/sendForm/handler.sendForm